### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by fac5** [ibadboy-net/ByeTyp#10]
不知道怎么回事在导入xml文件那里。
![空白页导入者就空白页了](https://user-images.githubusercontent.com/78854689/165928984-d499e1ce-9bfa-4970-ad72-a76fafe621a5.png)
![返回就提示](https://user-images.githubusercontent.com/78854689/165928894-b2ee0d1c-59bc-4d76-9e65-3736734086e6.png)

**Comment by jkjoy** [comment]
这是你wordpress服务器的问题
