### ISSUE TITLE
在WordPress中导入xml后数据库报错

### ISSUE THREAD

**Issue by vnwnv** [ibadboy-net/ByeTyp#2]
已修改
可能是因为phpmyadmin版本问题，正在尝试

**Comment by sunxiyuan** [comment]
可否提供详细的报错信息？
包括：tp和wp的版本、PHP和数据库的版本、具体的报错输出

**Comment by vnwnv** [comment]
已解决
php7.x与低版本phpmyadmin搭配时，在这种情况下修改数据库会报错。最好的办法就是升级phpmyadmin

错误日志
`Warning in ./libraries/config/FormDisplay.php#661
 "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?

Backtrace

./vendor/composer/ClassLoader.php#444: include()
./vendor/composer/ClassLoader.php#322: Composer\Autoload\includeFile(string '/www/server/phpmyadmin/phpmyadmin_554d1971cd2fc3fd/vendor/composer/../..//libraries/config/FormDisplay.php')
Composer\Autoload\ClassLoader->loadClass(string 'PMA\\libraries\\config\\FormDisplay')
./libraries/config/PageSettings.php#76: spl_autoload_call(string 'PMA\\libraries\\config\\FormDisplay')
./libraries/config/PageSettings.php#215: PMA\libraries\config\PageSettings->__construct(string 'DbStructure')
./libraries/controllers/database/DatabaseStructureController.php#163: PMA\libraries\config\PageSettings::showGroup(string 'DbStructure')
./db_structure.php#40: PMA\libraries\controllers\database\DatabaseStructureController->indexAction()
./index.php#80: include(./db_structure.php)`
