### ISSUE TITLE
导出数据出错

### ISSUE THREAD

**Issue by woshixiaoxiang** [ibadboy-net/ByeTyp#3]
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 53248 bytes) in /www/wwwroot/xxxxvar/Typecho/Db/Adapter/Pdo.php on line 102

**Comment by sunxiyuan** [comment]
怀疑是你数据库体积太大了。可以加我qq：1642491905，给你单独定制一个程序转换数据。
假如说你的数据库体积小于10MB，那么请把网站的备份文件除去附件后发到我邮箱：sxy@ibadboy.net，我需要用你的网站复现一下bug。
